config/routes.rb
Rails.application.routes.draw do
  root :to => redirect('/users/sign_in')
  devise_for :users, :controllers => {:registrations => "registrations"}

  get 'relationships', to: 'relationships#list'
  get 'relationships/:id', to: 'relationships#show'
  #get 'relationships/:id/new', to: 'relationships#new'
  get ':controller(/:action(/:id))'
  # resources :users, :relationships

  resources :relationships do
    resources :entries, shallow: true
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :entry, :class_name => "Entry", :foreign_key => "entry_id"
  belongs_to :author, :class_name => "User", :foreign_key => "author_id"

  before_create :set_created_at_to_now

  def set_created_at_to_now
    self.created_at = Time.now
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base

  belongs_to :author, :class_name => "User", :foreign_key => "author_id"
  has_many :comments, -> { order "created_at DESC" }

  before_create :set_created_at_to_now

  def set_created_at_to_now
    self.created_at = Time.now if !self.created_at
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

  belongs_to :mentor, class_name: "User", foreign_key: "mentor_id"
  belongs_to :mentee, class_name: "User", foreign_key: "mentee_id"
  has_many :entries, -> { order "created_at DESC" }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :admin, :mentor, :mentee]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def mentee_relationship
    Relationship.find_by_mentee_id( self.id )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :allow_responsive_is_iframe

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end


  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "Access denied."
    redirect_to (request.referrer || root_path)
  end

  def allow_responsive_is_iframe
    response.headers['X-Frame-Options'] = 'ALLOW-FROM http://responsive.is/'
  end

  def after_sign_in_path_for(resource)
    case current_user.role
    when 'mentee'
      "/relationships/#{current_user.mentee_relationship.id}"
    when 'mentor'
      '/relationships'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsControllerController < ApplicationController
  before_filter :authenticate_user!

  def create
    Relationship.find(params[:relationship_id]).entries.find(params[:entry]).comments <<
              Comment.new(text: params[:text], author: current_user)
    redirect_to "/relationships/#{params[:relationship_id]}"
  end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @relationship = Relationship.find(params[:relationship_id])
  end

  def create
    Relationship.find(params[:relationship_id]).entries <<
              Entry.new(
                  text: params[:text],
                  author: current_user,
                  entry_type: params[:entry_type],
                  question: params[:question],
                  emoticon: params[:emoticon]
                  )
    redirect_to "/relationships/#{params[:relationship_id]}"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to "/relationships/#{current_user.mentee_relationship.id}" if current_user.role.eql? 'mentee'
      redirect_to '/relationships' if current_user.role.eql? 'mentor'
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_filter :authenticate_user!

  def list
    # list the current relationships for the current user (assumed mentor)
    @relationships = Relationship.where(mentor: current_user)
  end

  def create_entry
    relationship_id = Relationship.find_by_mentee_id( current_user.id ).id
    entry_type = params[:entry_type]
    if entry_type == 'emoticon'
      text = params[:emoticon]
    else
      text = params[:text]
    end
    entry = Entry.new(
        author: current_user,
        relationship_id: relationship_id,
        text: text,
        entry_type: entry_type,
        question: params[:question]
        )
    entry.save!
    redirect_to action: 'index'
  end

  def show
    @entries_by_date = Relationship.find(params[:id]).entries.inject({}) { |r, e|
      r[e.created_at.strftime("%A %d %B %Y")]||=[]; r[e.created_at.strftime("%A %d %B %Y")] << e; r
    }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized, except: [:show]

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/comments_controller_helper.rb
module CommentsControllerHelper
end

app/views/entries/new.html.erb
<div id="emoticon-entry" class="row" style="display:none;height:100%;">
  <form role="form" style="width:100%;height:100%;" method="post" action="/relationships/<%=@relationship.id%>/entries">
    <div id="emoticon-entry-icon" style="height:33%;" name="emoticon"></div>
    <textarea class="form-control" name="text" rows="3" placeholder="How are you?"></textarea>
    <button type="submit" class="btn btn-default" style="width:100%;">Submit</button>
    <input type="hidden" name="entry_type" value="emoticon">
    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token">
    <input id="emoticon-entry-emoticon" type="hidden" name="emoticon">
  </form>
</div>

<div id="new-entry" class="row" style="display:none;height:100%;">
  <form role="form" style="width:100%;height:100%;" method="post" action="/relationships/<%=@relationship.id%>/entries">
    <textarea class="form-control" name="text" rows="3" placeholder="How are you?"></textarea>
    <button type="submit" class="btn btn-default" style="width:100%;">Submit</button>
    <input type="hidden" name="entry_type" value="post">
    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token">
  </form>
</div>

<div id="main-menu" style="height:100%;">
<div class="row" style="height:33%;">
  <div id="carousel-emoticon" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner">
      <div class="item active angry" data-emoticon="angry">
        &nbsp;
      </div>
<div class="item cheeky" data-emoticon="cheeky">
  &nbsp;
</div>
<div class="item confused" data-emoticon="confused">
  &nbsp;
</div>
<div class="item happy" data-emoticon="happy">
  &nbsp;
</div>
<div class="item hmm" data-emoticon="hmm">
  &nbsp;
</div>
<div class="item meh" data-emoticon="meh">
  &nbsp;
</div>
<div class="item sad" data-emoticon="sad">
  &nbsp;
</div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-emoticon" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-emoticon" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div class="row" style="height:33%;">
  <div id="carousel-question" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner" style="background-color:#16C1F3;">
      <div class="item active">
        <p>
          How are you feeling?
        </p>
      </div>
      <div class="item">
        <p>
          What are you doing today?
        </p>
      </div>
      <div class="item">
        <p>
          Anything new?
        </p>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-question" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-question" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div id="post-item" class="row">
  <div class="col-xs-12">
    <span class="glyphicon glyphicon-comment"></span>
  </div>
</div>
</div>

app/views/home/_emotion.html.erb
<div class="row" style="height:33%;">
  <div id="carousel-emoticon" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner">
      <div class="item active angry">
        &nbsp;
      </div>
<div class="item cheeky">
  &nbsp;
</div>
<div class="item confused">
  &nbsp;
</div>
<div class="item happy">
  &nbsp;
</div>
<div class="item hmm">
  &nbsp;
</div>
<div class="item meh">
  &nbsp;
</div>
<div class="item sad">
  &nbsp;
</div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-emoticon" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-emoticon" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div class="row" style="height:33%;">
  <div id="carousel-question" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner" style="background-color:#16C1F3;">
      <div class="item active">
        <p>
          How are you feeling?
        </p>
      </div>
      <div class="item">
        <p>
          What are you doing today?
        </p>
      </div>
      <div class="item">
        <p>
          Anything new?
        </p>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-question" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-question" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div id="post-item" class="row">
  <div class="col-xs-12">
    <span class="glyphicon glyphicon-comment"></span>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: "emotion" %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
        <% if current_user.role == "mentee" %>
          <%= link_to 'Home', new_relationship_entry_path(current_user.mentee_relationship), class: 'navbar-brand' %>
        <% else %>
          <%= link_to 'Home', relationships_path(), class: 'navbar-brand' %>
        <% end %>
      <% else %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' %>
      <% end %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <% if current_user.role.eql? "mentee" %>
    <li><%= link_to "Feed", relationship_path(current_user.mentee_relationship) %></li>
  <% end %>
  <li><%= link_to "#{current_user.name} (Sign out)", destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Users', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Startout" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Startout" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body data-no-turbolink="true">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Startout" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Startout" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <main role="main" style="background-color: #F6006D; margin-top: 0">
       <%= yield %>
    </main>
  </body>
</html>

app/views/relationships/entry_new.html.erb
<div id="emoticon-entry" class="row" style="display:none;height:100%;">
  <form role="form" style="width:100%;height:100%;" method="post" action="/relationships/<%=@relationship.id%>/entries">
    <div id="emoticon-entry-icon" style="height:33%;" name="emoticon"></div>
    <textarea class="form-control" name="text" rows="3" placeholder="How are you?"></textarea>
    <button type="submit" class="btn btn-default" style="width:100%;">Submit</button>
    <input type="hidden" name="entry_type" value="emoticon">
    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token">
    <input id="emoticon-entry-emoticon" type="hidden" name="emoticon">
  </form>
</div>

<div id="new-entry" class="row" style="display:none;height:100%;">
  <form role="form" style="width:100%;height:100%;" method="post" action="/relationships/<%=@relationship.id%>/entries">
    <textarea class="form-control" name="text" rows="3" placeholder="How are you?"></textarea>
    <button type="submit" class="btn btn-default" style="width:100%;">Submit</button>
    <input type="hidden" name="entry_type" value="post">
    <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token">
  </form>
</div>

<div id="main-menu" style="height:100%;">
<div class="row" style="height:33%;">
  <div id="carousel-emoticon" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner">
      <div class="item active angry" data-emoticon="angry">
        &nbsp;
      </div>
<div class="item cheeky" data-emoticon="cheeky">
  &nbsp;
</div>
<div class="item confused" data-emoticon="confused">
  &nbsp;
</div>
<div class="item happy" data-emoticon="happy">
  &nbsp;
</div>
<div class="item hmm" data-emoticon="hmm">
  &nbsp;
</div>
<div class="item meh" data-emoticon="meh">
  &nbsp;
</div>
<div class="item sad" data-emoticon="sad">
  &nbsp;
</div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-emoticon" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-emoticon" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div class="row" style="height:33%;">
  <div id="carousel-question" class="carousel slide" data-ride="carousel">

    <div class="carousel-inner" style="background-color:#16C1F3;">
      <div class="item active">
        <p>
          How are you feeling?
        </p>
      </div>
      <div class="item">
        <p>
          What are you doing today?
        </p>
      </div>
      <div class="item">
        <p>
          Anything new?
        </p>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-question" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-question" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
  </div>
</div>

<div id="post-item" class="row">
  <div class="col-xs-12">
    <span class="glyphicon glyphicon-comment"></span>
  </div>
</div>
</div>

app/views/relationships/index.erb
<div class="container">
  <row>
    <form role="form" method="post" action="/relationships">
      <textarea rows="3" name="text" class="form-control" placeholder="Post new entry"></textarea>
      <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token">
      <button type="submit" class="btn btn-default">Post</button>
    </form>
  </row>

  <% @relationship.entries.each do |entry| %>
  <div class="row">
    <div class="feed_entry_info col-xs-4 col-sm-2">
      <div class="entry_avatar pull-left">
        <img src="https://assets-cdn.github.com/images/modules/dashboard/bootcamp/octocat_fork.png?1a1dfcb9" alt="avatar image" class="img-circle img-responsive">
      </div>
      <div class="entry_author">
        <%= entry.author.name %>
      </div>
    </div>

    <div class="panel panel-default feed_entry col-xs-8 col-sm-10">
      <div class="panel-body feed_body">
        <%= entry.text %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/relationships/list.html.erb
<div class="container">
  <div class="row">
    <h3>Relationships</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @relationships.each do |relationship| %>
            <tr>
              <td>
                <img src="<%= image_path(relationship.mentee.avatar_name) %>" alt="avatar image" class="img-responsive">
              </td>
              <td style="vertical-align:middle"><%= link_to(relationship.mentee.name, :controller => 'relationships', :action => 'show', :id => relationship.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/relationships/show.html.erb
  <% @entries_by_date.each do |date, entries| %>
    <div class="row">
      <div class="feed_entry_info col-xs-12 col-sm-12" style="background-color:#404041;color:white;height:36px;">
        <%= date %>
      </div>
    </div>
    <% entries.each do |entry| %>
    <div class="row">
      <div class="feed_entry_info col-xs-2 col-sm-2">
        <div class="entry_avatar pull-left">
          <img src="<%= image_path(entry.author.avatar_name) %>" alt="avatar image" class="img-circle img-responsive">
        </div>
      </div>

      <div class="panel panel-default feed_entry col-xs-9 col-sm-9">

        <div class="panel-body feed_body">
        <% if(entry.entry_type === 'emoticon') %>
        <div class="<%= entry.emoticon %> emoticon pull-left" style="height:3em;width:3em;"></div>
        <% end %>
          <%= entry.text %>
        </div>
        <% if(entry.comments.length > 0) %>
        <label>Comments</label>
        <% end %>
        <% entry.comments.each do |comment| %>
        <div class="panel panel-default feed_entry col-xs-12 col-sm-12">
          <div class="panel-body feed_body">
            <%= comment.author.name %>: <%= comment.text %>
          </div>
        </div>
      <% end %>
      </div>

    </div>
    <% end %>
  <% end %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>